version: '3.8'

services:
  communication-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: communication-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DB_URL=${MONGO_URL}  # Use Railway's injected variable
      - LOG_LEVEL=info
    healthcheck:  # Add health check
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - mongo
    networks:
      - communication-network

  mongo:
    image: mongo:5.0
    container_name: communication-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - communication-mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=communication_db
    networks:
      - communication-network

volumes:
  communication-mongo-data:

networks:
  communication-network:
    driver: bridge